apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: eds.csi.sangfor.com
spec:
  attachRequired: false
---
# This YAML defines all API objects to create RBAC roles for csi node plugin.
kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-nasplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-nasplugin
  template:
    metadata:
      labels:
        app: csi-nasplugin
    spec:
      tolerations:
      - operator: Exists
      priorityClassName: system-node-critical
      serviceAccount: admin
      hostNetwork: true
      hostPID: true
      containers:
      - name: driver-registrar
        image: registry.cn-sz.sangfor.com/eds/csi-node-driver-registrar:v1.1.0
        imagePullPolicy: "IfNotPresent"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm -rf /registration/eds.csi.sangfor.com /registration/eds.csi.sangfor.com-reg.sock"]
        args:
        - "--v=5"
        - "--csi-address=/var/lib/kubelet/plugins/eds.csi.sangfor.com/csi.sock"
        - "--kubelet-registration-path=/var/lib/kubelet/plugins/eds.csi.sangfor.com/csi.sock"
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        volumeMounts:
        - name: kubelet-dir
          mountPath: /var/lib/kubelet/
        - name: registration-dir
          mountPath: /registration

      - name: csi-nasplugin
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        image: registry.cn-sz.sangfor.com/eds/csi-nasplugin:v1.14.6-cea9638
        imagePullPolicy: "IfNotPresent"
        args:
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--loglevel=info"
        - "--nodeid=localhost"
        - "--driver=eds.csi.sangfor.com"
        env:
        - name: CSI_ENDPOINT
          value: unix://var/lib/kubelet/plugins/eds.csi.sangfor.com/csi.sock
        volumeMounts:
        - name: kubelet-dir
          mountPath: /var/lib/kubelet/
          mountPropagation: "Bidirectional"
        - mountPath: /var/log/
          name: host-log
        - name: etc
          mountPath: /host/etc
      volumes:
      - name: kubelet-dir
        hostPath:
          path: /var/lib/kubelet/
          type: Directory
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: DirectoryOrCreate
      - name: host-log
        hostPath:
          path: /var/log/
      - name: etc
        hostPath:
          path: /etc
  updateStrategy:
    type: RollingUpdate
