apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nas-static
  labels:
    app: centos7
spec:
  selector:
    matchLabels:
      app: centos7
  template:
    metadata:
      labels:
        app: centos7
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: centos7
        image: centos:7.4.1708
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        volumeMounts:
          - name: nas-csi-pv-static
            mountPath: "/data"
      volumes:
        - name: nas-csi-pv-static
          persistentVolumeClaim:
            claimName: nas-csi-pvc-static
