apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-csi-pvc-static
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      eds-pvname: nas-csi-pv-static
